{% set name = "python-workflow-definition" %}
{% set version = "0.0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_workflow_definition-{{ version }}.tar.gz
  sha256: c3219ca13fe2984e038f9b6e485d0348afec1681865657e102c1126fc6d9bc80
  patches:
    - pyproject.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - aiida-workgraph >=0.5.1,<=0.5.2
    - httpcore >=0.15.0
    - numpy >=1.21,<2
    - jobflow >=0.1.18,<=0.1.19
    - pyiron_base >=0.11.10,<=0.11.11

test:
  imports:
    - python_workflow_definition
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Python Workflow Definition - workflow interoperability for aiida, jobflow and pyiron
  home: http://pythonworkflow.github.io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
